In [1]:
pip install pandas

Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
pip install openpyxl

Requirement already satisfied: openpyxl in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
file_path =r"C:\Users\ELCOT\Downloads\banking_loan_portfolio_20000_rows_MESSY.xlsx"

In [8]:
excel_file = pd.ExcelFile(file_path)

In [13]:
print("Available Sheets:")
print(excel_file.sheet_names)

Available Sheets:
['Customers', 'Loan_Applications', 'Loans', 'Loan_Payments', 'Credit_History', 'Branches', 'Collateral', 'Loan_Status_History', 'Loan_Recovery']

In [10]:
customers = pd.read_excel(file_path, sheet_name="Customers")
loan_applications=pd.read_excel(file_path, sheet_name="Loan_Applications")
loans=pd.read_excel(file_path, sheet_name="Loans")
loan_payments=pd.read_excel(file_path, sheet_name="Loan_Payments")
credit_history=pd.read_excel(file_path, sheet_name="Credit_History")
branches=pd.read_excel(file_path, sheet_name="Branches")
collateral=pd.read_excel(file_path, sheet_name="Collateral")
loan_status_history=pd.read_excel(file_path, sheet_name="Loan_Status_History")
loan_recovery=pd.read_excel(file_path, sheet_name="Loan_Recovery")

In [19]:
print(customers.shape)
print(loan_applications.shape)
print(loans.shape)
print(loan_payments.shape)
print(credit_history.shape)
print(branches.shape)
print(collateral.shape)
print(loan_status_history.shape)
print(loan_recovery.shape)

(1212, 15)
(2412, 8)
(2112, 12)
(7212, 8)
(1212, 7)
(32, 6)
(909, 9)
(4512, 8)
(474, 9)

In [21]:
customers.head()

,customer_id,first_name,last_name,gender,age,date_of_birth,marital_status,occupation,annual_income,monthly_income,city,state,customer_segment,credit_score,account_open_date
0,1,Pooja,Verma,Male,41,1983-05-16,Married,Salaried,796148.16,66345.68,Mysuru,Karnataka,Affluent,618,2015-09-05
1,2,Rahul,Rao,Female,40,1984-11-11,Single,Salaried,693082.86,57756.90,Lucknow,Uttar Pradesh,Retail,706,2022-12-18
2,3,Aditya,Gupta,Female,59,1965-03-21,Married,Salaried,702964.59,58580.38,Mumbai,Maharashtra,Affluent,741,2019-03-06
3,4,Pooja,Sharma,Female,34,1990-07-06,Married,Self-Employed,740797.23,61733.10,New Delhi,Delhi,Affluent,645,2022-03-11
4,5,Diya,Menon,Male,34,1990-12-02,Married,Self-Employed,289463.41,24121.95,Chennai,Tamil Nadu,Retail,613,2019-05-30

In [22]:
loan_applications.head()

,application_id,customer_id,loan_type,requested_amount,application_date,approval_status,rejection_reason,processing_days
0,1,136,Personal,669558.78,2024-01-24,Approved,Not Available,2
1,2,67,Education,1456486.70,2024-07-20,Approved,Not Available,6
2,3,166,Auto,464437.51,2022-11-23,Approved,Not Available,3
3,4,495,Home,982320.05,2024-01-16,Approved,Not Available,7
4,5,1093,Home,3188991.75,2022-05-12,Approved,Not Available,7

In [24]:
loans.head()

,loan_id,customer_id,branch_id,loan_type,application_date,approval_date,loan_amount,interest_rate,loan_tenure_months,emi_amount,loan_status,outstanding_balance
0,1,579,21,Personal,2022-09-13,2022-09-28,1224338.99,12.04,71,24192.28,ACTIVE,1102872.46
1,2,714,8,Gold,2024-09-06,2024-09-13,117920.89,9.69,35,3881.17,Active,31199.07
2,3,933,25,Personal,2024-02-15,2024-02-19,-25000.00,11.54,51,2935.25,Active,62643.43
3,4,41,22,Personal,2023-04-18,2023-04-21,319137.59,13.87,44,9294.09,Active,48135.54
4,5,468,9,Home,2022-03-15,2022-03-30,3050284.65,7.17,182,27537.86,Active,2097125.95

In [25]:
loan_payments.head()

,payment_id,loan_id,payment_date,emi_due_date,payment_amount,payment_status,days_overdue,penalty_amount
0,1,459,2026-02-23,2026-02-23,51993.22,Paid,0.0,0.00
1,2,345,2024-12-03,2024-11-23,16902.43,Late,10.0,1690.24
2,3,1333,2023-08-18,2023-08-18,27815.68,Paid,0.0,0.00
3,4,382,2023-02-19,2023-02-19,56941.43,Paid,0.0,0.00
4,5,167,2024-09-03,2024-08-21,20456.88,Late,13.0,2659.39

In [26]:
credit_history.head()

,credit_id,customer_id,credit_score,previous_loans,previous_defaults,active_loans,credit_utilization
0,1,1,618,3.0,0,2.0,48.39
1,2,2,706,3.0,0,1.0,40.19
2,3,3,741,1.0,0,1.0,34.68
3,4,4,645,4.0,0,1.0,87.26
4,5,5,613,1.0,0,0.0,150.00

In [27]:
branches.head()

   branch_id          branch_name        city       state region  manager_name
0          1     Chennai Branch 1     Chennai  Tamil Nadu  South   Manager 001
1          2  Coimbatore Branch 1  Coimbatore  Tamil Nadu  South   Manager 002
2          3     Madurai Branch 1         NaN  Tamil Nadu  South   Manager 003
3          4   Bengaluru Branch 1         NaN   Karnataka  South   Manager 004
4          5      Mysuru Branch 1      Mysuru   Karnataka  South   Manager 005

In [28]:
collateral.head()

,collateral_id,loan_id,collateral_type,collateral_value,valuation_date,ownership_status,collateral_status,loan_type,valuation_source
0,1,628,Property,723511.34,2022-08-07,Customer Owned,Active,Auto,Bank Approved Valuer
1,2,1503,Vehicle,1095362.90,2024-10-26,Customer Owned,Active,Business,Bank Approved Valuer
2,3,1073,Property,981749.08,2025-05-09,Customer Owned,Active,Business,Bank Approved Valuer
3,4,1173,Gold,2385655.56,2024-03-23,Customer Owned,Active,Home,Bank Approved Valuer
4,5,1341,Property,544066.55,2023-07-14,Customer Owned,Active,Auto,Bank Approved Valuer

In [29]:
loan_status_history.head()

,status_history_id,loan_id,status_date,previous_status,new_status,days_in_status,reason,recorded_by
0,1,55,2024-07-03,Recovery,Closed,82,Recovery Initiated,Collections Team
1,2,438,2026-06-11,Active,Overdue,138,Risk Review,Collections Team
2,3,920,2022-07-18,Active,Active,60,Recovery Initiated,Collections Team
3,4,641,2024-07-31,Active,Active,100,Risk Review,Collections Team
4,5,936,2025-01-06,Active,Closed,176,Payment Missed,Collections Team

In [31]:
loan_recovery.head()

,recovery_id,loan_id,recovery_date,recovery_amount,recovery_method,recovery_status,recovery_cost,recovery_officer,remarks
0,1,1404,2024-06-13,245952.56,Legal Recovery,Full,5123.87,Officer 344,Settlement payment
1,2,1259,2023-11-25,56537.88,Direct Payment,Partial,1463.15,Officer 324,Collateral proceeds
2,3,767,2024-11-06,346429.40,Settlement,Partial,9529.52,Officer 106,Settlement payment
3,4,58,2027-03-07,418822.92,Settlement,Full,6281.55,Officer 176,Legal collection
4,5,321,2024-10-16,88209.34,Settlement,Partial,6336.01,Officer 278,Collateral proceeds