In [1]:
pip install pandas

Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
pip install openpyxl

Requirement already satisfied: openpyxl in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
file_path =r"C:\Users\ELCOT\Downloads\banking_loan_portfolio_messy_data.xlsx"

In [5]:
excel_file = pd.ExcelFile(file_path)

In [6]:
print("Available Sheets:")
print(excel_file.sheet_names)

Available Sheets:
['Customers', 'Loan_Applications', 'Loans', 'Loan_Payments', 'Credit_History', 'Branches', 'Collateral', 'Loan_Status_History', 'Loan_Recovery']

In [7]:
customers = pd.read_excel(file_path, sheet_name="Customers")
loan_applications=pd.read_excel(file_path, sheet_name="Loan_Applications")
loans=pd.read_excel(file_path, sheet_name="Loans")
loan_payments=pd.read_excel(file_path, sheet_name="Loan_Payments")
credit_history=pd.read_excel(file_path, sheet_name="Credit_History")
branches=pd.read_excel(file_path, sheet_name="Branches")
collateral=pd.read_excel(file_path, sheet_name="Collateral")
loan_status_history=pd.read_excel(file_path, sheet_name="Loan_Status_History")
loan_recovery=pd.read_excel(file_path, sheet_name="Loan_Recovery")

In [8]:
print(customers.shape)
print(loan_applications.shape)
print(loans.shape)
print(loan_payments.shape)
print(credit_history.shape)
print(branches.shape)
print(collateral.shape)
print(loan_status_history.shape)
print(loan_recovery.shape)

(1200, 15)
(2400, 8)
(2100, 12)
(7200, 8)
(1200, 7)
(30, 6)
(900, 9)
(4500, 8)
(470, 9)

In [9]:
customers.head()

,customer_id,first_name,last_name,gender,age,date_of_birth,marital_status,occupation,annual_income,monthly_income,city,state,customer_segment,credit_score,account_open_date
0,1,Pooja,Verma,Male,41,1983-05-16,Married,Salaried,796148.16,66345.68,Mysuru,Karnataka,Affluent,618,2015-09-05
1,2,Rahul,Rao,Female,40,1984-11-11,Single,Salaried,693082.86,57756.90,Lucknow,Uttar Pradesh,Retail,706,2022-12-18
2,3,Aditya,Gupta,Female,59,1965-03-21,Married,Salaried,702964.59,58580.38,Mumbai,Maharashtra,Affluent,741,2019-03-06
3,4,Pooja,Sharma,Female,34,1990-07-06,Married,Self-Employed,740797.23,61733.10,New Delhi,Delhi,Affluent,645,2022-03-11
4,5,Diya,Menon,Male,34,1990-12-02,Married,Self-Employed,289463.41,24121.95,Chennai,Tamil Nadu,Retail,613,2019-05-30

In [10]:
loan_applications.head()

,application_id,customer_id,loan_type,requested_amount,application_date,approval_status,rejection_reason,processing_days
0,1,136,Personal,669558.78,2024-01-24,Approved,Not Available,2
1,2,67,Education,1456486.70,2024-07-20,Approved,Not Available,6
2,3,166,Auto,464437.51,2022-11-23,Approved,Not Available,3
3,4,495,Home,982320.05,2024-01-16,Approved,Not Available,7
4,5,1093,Home,3188991.75,2022-05-12,Approved,Not Available,7

In [11]:
loans.head()

,loan_id,customer_id,branch_id,loan_type,application_date,approval_date,loan_amount,interest_rate,loan_tenure_months,emi_amount,loan_status,outstanding_balance
0,1,579,21,Personal,2022-09-13,2022-09-28,1224338.99,12.04,71,24192.28,Active,1102872.46
1,2,714,8,Gold,2024-09-06,2024-09-13,117920.89,9.69,35,3881.17,Active,31199.07
2,3,933,25,Personal,2024-02-15,2024-02-19,117881.89,11.54,51,2935.25,Active,62643.43
3,4,41,22,Personal,2023-04-18,2023-04-21,319137.59,13.87,44,9294.09,Active,48135.54
4,5,468,9,Home,2022-03-15,2022-03-30,3050284.65,7.17,182,27537.86,Active,2097125.95

In [13]:
loan_payments.head()

,payment_id,loan_id,payment_date,emi_due_date,payment_amount,payment_status,days_overdue,penalty_amount
0,1,459,2026-02-23,2026-02-23,51993.22,Paid,0,0.00
1,2,345,2024-12-03,2024-11-23,16902.43,Late,10,1690.24
2,3,1333,2023-08-18,2023-08-18,27815.68,Paid,0,0.00
3,4,382,2023-02-19,2023-02-19,56941.43,Paid,0,0.00
4,5,167,2024-09-03,2024-08-21,20456.88,Late,13,2659.39

In [14]:
credit_history.head()

,credit_id,customer_id,credit_score,previous_loans,previous_defaults,active_loans,credit_utilization
0,1,1,618,3,0,2,48.39
1,2,2,706,3,0,1,40.19
2,3,3,741,1,0,1,34.68
3,4,4,645,4,0,1,87.26
4,5,5,613,1,0,0,52.85

In [16]:
branches.head()

   branch_id          branch_name        city       state region manager_name
0          1     Chennai Branch 1     Chennai  Tamil Nadu  South  Manager 001
1          2  Coimbatore Branch 1  Coimbatore  Tamil Nadu  South  Manager 002
2          3     Madurai Branch 1     Madurai  Tamil Nadu  South  Manager 003
3          4   Bengaluru Branch 1   Bengaluru   Karnataka  South  Manager 004
4          5      Mysuru Branch 1      Mysuru   Karnataka  South  Manager 005

In [17]:
collateral.head()

,collateral_id,loan_id,collateral_type,collateral_value,valuation_date,ownership_status,collateral_status,loan_type,valuation_source
0,1,628,Property,723511.34,2022-08-07,Customer Owned,Active,Auto,Bank Approved Valuer
1,2,1503,Vehicle,1095362.90,2024-10-26,Customer Owned,Active,Business,Bank Approved Valuer
2,3,1073,Property,981749.08,2025-05-09,Customer Owned,Active,Business,Bank Approved Valuer
3,4,1173,Gold,2385655.56,2024-03-23,Customer Owned,Active,Home,Bank Approved Valuer
4,5,1341,Property,544066.55,2023-07-14,Customer Owned,Active,Auto,Bank Approved Valuer

In [18]:
loan_status_history.head()

,status_history_id,loan_id,status_date,previous_status,new_status,days_in_status,reason,recorded_by
0,1,55,2024-07-03,Recovery,Closed,82,Recovery Initiated,Collections Team
1,2,438,2026-06-11,Active,Overdue,138,Risk Review,Collections Team
2,3,920,2022-07-18,Active,Active,60,Recovery Initiated,Collections Team
3,4,641,2024-07-31,Active,Active,100,Risk Review,Collections Team
4,5,936,2025-01-06,Active,Closed,176,Payment Missed,Collections Team

In [19]:
loan_recovery.head()

,recovery_id,loan_id,recovery_date,recovery_amount,recovery_method,recovery_status,recovery_cost,recovery_officer,remarks
0,1,1404,2024-06-13,245952.56,Legal Recovery,Full,5123.87,Officer 344,Settlement payment
1,2,1259,2023-11-25,56537.88,Direct Payment,Partial,1463.15,Officer 324,Collateral proceeds
2,3,767,2024-11-06,346429.40,Settlement,Partial,9529.52,Officer 106,Settlement payment
3,4,58,2027-03-07,418822.92,Settlement,Full,6281.55,Officer 176,Legal collection
4,5,321,2024-10-16,88209.34,Settlement,Partial,6336.01,Officer 278,Collateral proceeds

In [18]:
customers.info()
loan_applications.info()
loans.info()
loan_payments.info()
credit_history.info()
branches.info()
collateral.info()
loan_status_history.info()
loan_recovery.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        1200 non-null   int64
 1   first_name         1200 non-null   str
 2   last_name          1200 non-null   str
 3   gender             1200 non-null   str
 4   age                1200 non-null   int64
 5   date_of_birth      1200 non-null   datetime64[us]
 6   marital_status     1200 non-null   str
 7   occupation         1200 non-null   str
 8   annual_income      1199 non-null   float64
 9   monthly_income     1199 non-null   float64
 10  city               1200 non-null   str
 11  state              1200 non-null   str
 12  customer_segment   1200 non-null   str
 13  credit_score       1200 non-null   int64
 14  account_open_date  1200 non-null   datetime64[us]
dtypes: datetime64[us](2), float64(2), int64(3), str(8)
memory usage: 140.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   application_id    2400 non-null   int64
 1   customer_id       2400 non-null   int64
 2   loan_type         2400 non-null   str
 3   requested_amount  2400 non-null   float64
 4   application_date  2400 non-null   datetime64[us]
 5   approval_status   2400 non-null   str
 6   rejection_reason  2400 non-null   str
 7   processing_days   2400 non-null   int64
dtypes: datetime64[us](1), float64(1), int64(3), str(3)
memory usage: 150.1 KB
<class 'pandas.DataFrame'>
RangeIndex: 2100 entries, 0 to 2099
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   loan_id              2100 non-null   int64
 1   customer_id          2100 non-null   int64
 2   branch_id            2100 non-null   int64
 3   loan_type            2100 non-null   str
 4   application_date     2100 non-null   datetime64[us]
 5   approval_date        2100 non-null   datetime64[us]
 6   loan_amount          2099 non-null   float64
 7   interest_rate        2100 non-null   float64
 8   loan_tenure_months   2100 non-null   int64
 9   emi_amount           2100 non-null   float64
 10  loan_status          2100 non-null   str
 11  outstanding_balance  2100 non-null   float64
dtypes: datetime64[us](2), float64(4), int64(4), str(2)
memory usage: 197.0 KB
<class 'pandas.DataFrame'>
RangeIndex: 7200 entries, 0 to 7199
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      7200 non-null   int64
 1   loan_id         7200 non-null   int64
 2   payment_date    7200 non-null   datetime64[us]
 3   emi_due_date    7200 non-null   datetime64[us]
 4   payment_amount  7199 non-null   float64
 5   payment_status  7200 non-null   str
 6   days_overdue    7200 non-null   int64
 7   penalty_amount  7200 non-null   float64
dtypes: datetime64[us](2), float64(2), int64(3), str(1)
memory usage: 450.1 KB
<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   credit_id           1200 non-null   int64
 1   customer_id         1200 non-null   int64
 2   credit_score        1200 non-null   int64
 3   previous_loans      1200 non-null   int64
 4   previous_defaults   1200 non-null   int64
 5   active_loans        1200 non-null   int64
 6   credit_utilization  1200 non-null   float64
dtypes: float64(1), int64(6)
memory usage: 65.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   branch_id     30 non-null     int64
 1   branch_name   30 non-null     str
 2   city          30 non-null     str
 3   state         30 non-null     str
 4   region        30 non-null     str
 5   manager_name  30 non-null     str
dtypes: int64(1), str(5)
memory usage: 1.5 KB
<class 'pandas.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collateral_id      900 non-null    int64
 1   loan_id            900 non-null    int64
 2   collateral_type    900 non-null    str
 3   collateral_value   900 non-null    float64
 4   valuation_date     900 non-null    datetime64[us]
 5   ownership_status   900 non-null    str
 6   collateral_status  900 non-null    str
 7   loan_type          900 non-null    str
 8   valuation_source   900 non-null    str
dtypes: datetime64[us](1), float64(1), int64(2), str(5)
memory usage: 63.4 KB
<class 'pandas.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   status_history_id  4500 non-null   int64
 1   loan_id            4500 non-null   int64
 2   status_date        4500 non-null   datetime64[us]
 3   previous_status    4500 non-null   str
 4   new_status         4500 non-null   str
 5   days_in_status     4500 non-null   int64
 6   reason             4500 non-null   str
 7   recorded_by        4500 non-null   str
dtypes: datetime64[us](1), int64(3), str(4)
memory usage: 281.4 KB
<class 'pandas.DataFrame'>
RangeIndex: 470 entries, 0 to 469
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   recovery_id       470 non-null    int64
 1   loan_id           470 non-null    int64
 2   recovery_date     470 non-null    datetime64[us]
 3   recovery_amount   469 non-null    float64
 4   recovery_method   470 non-null    str
 5   recovery_status   470 non-null    str
 6   recovery_cost     470 non-null    float64
 7   recovery_officer  470 non-null    str
 8   remarks           470 non-null    str
dtypes: datetime64[us](1), float64(2), int64(2), str(4)
memory usage: 33.2 KB

In [19]:
print("Customers")
display(customers.describe())
print("Loan_applications")
display(loan_applications.describe())
print("Loans")
display(loans.describe())
print("Loan_payments")
display(loan_payments.describe())
print("Credit_history")
display(credit_history.describe())
print("Branches")
display(branches.describe())
print("Collateral")
display(collateral.describe())
print("Loan_status_history")
display(loan_status_history.describe())
print("Loan_recovery")

Customers

,customer_id,age,date_of_birth,annual_income,monthly_income,credit_score,account_open_date
count,1200.000000,1200.000000,1200,1.199000e+03,1199.000000,1200.000000,1200
mean,600.500000,42.864167,1981-08-09 23:44:24,7.524208e+05,62711.761710,688.693333,2019-12-26 14:56:24
min,1.000000,-5.000000,1959-03-04 00:00:00,1.800000e+05,15000.000000,398.000000,2015-01-01 00:00:00
25%,300.750000,32.000000,1970-09-09 00:00:00,4.397616e+05,36646.805000,639.000000,2017-06-12 00:00:00
50%,600.500000,43.000000,1981-09-07 12:00:00,6.346171e+05,52996.570000,686.000000,2019-11-28 00:00:00
75%,900.250000,54.000000,1992-06-11 00:00:00,9.430416e+05,78586.800000,739.000000,2022-05-28 00:00:00
max,1200.000000,65.000000,2003-11-10 00:00:00,3.444182e+06,287015.160000,950.000000,2024-12-27 00:00:00
std,346.554469,12.839773,NaN,4.652853e+05,38769.705573,74.432326,NaN

Loan_applications

,application_id,customer_id,requested_amount,application_date,processing_days
count,2400.000000,2400.00000,2.400000e+03,2400,2400.000000
mean,1200.500000,605.32625,1.995266e+06,2023-06-27 06:07:48,4.700833
min,1.000000,1.00000,3.377813e+04,2022-01-01 00:00:00,1.000000
25%,600.750000,290.00000,5.850575e+05,2022-09-28 00:00:00,2.000000
50%,1200.500000,610.00000,1.277112e+06,2023-06-18 00:00:00,5.000000
75%,1800.250000,933.00000,3.372303e+06,2024-03-20 12:00:00,7.000000
max,2400.000000,1199.00000,5.000000e+06,2024-12-30 00:00:00,17.000000
std,692.964646,358.46093,1.715308e+06,NaN,2.739883

Loans

,loan_id,customer_id,branch_id,application_date,approval_date,loan_amount,interest_rate,loan_tenure_months,emi_amount,outstanding_balance
count,2100.000000,2100.000000,2100.000000,2100,2100,2.099000e+03,2100.000000,2100.000000,2100.000000,2.100000e+03
mean,1050.500000,630.927619,15.650476,2023-06-30 18:03:25.714285,2023-07-08 18:15:46.285714,1.537551e+06,10.960967,93.699048,24047.940352,7.228302e+05
min,1.000000,1.000000,1.000000,2022-01-02 00:00:00,2022-01-07 00:00:00,2.664145e+04,5.000000,12.000000,861.900000,0.000000e+00
25%,525.750000,349.250000,9.000000,2022-10-02 00:00:00,2022-10-10 18:00:00,4.135353e+05,9.020000,56.000000,9524.027500,7.043118e+04
50%,1050.500000,640.000000,16.000000,2023-07-07 00:00:00,2023-07-15 12:00:00,9.672526e+05,10.875000,79.000000,17498.780000,3.373074e+05
75%,1575.250000,936.000000,23.000000,2024-03-25 12:00:00,2024-04-02 00:00:00,2.083576e+06,12.830000,117.250000,30879.025000,9.663017e+05
max,2100.000000,1200.000000,30.000000,2024-12-30 00:00:00,2025-01-11 00:00:00,6.000000e+06,75.000000,240.000000,187544.280000,5.976883e+06
std,606.362103,352.935869,8.561952,NaN,NaN,1.548239e+06,2.861789,51.934496,22075.794147,1.014339e+06

Loan_payments

,payment_id,loan_id,payment_date,emi_due_date,payment_amount,days_overdue,penalty_amount
count,7200.000000,7200.000000,7200,7200,7199.000000,7200.000000,7200.000000
mean,3600.500000,802.465694,2025-06-23 21:03:24,2025-06-17 06:19:48,24442.892053,6.612222,1630.513972
min,1.000000,1.000000,2022-02-15 00:00:00,2022-02-15 00:00:00,826.430000,-10.000000,0.000000
25%,1800.750000,407.750000,2024-06-17 00:00:00,2024-06-10 18:00:00,9693.260000,0.000000,0.000000
50%,3600.500000,805.000000,2025-06-19 00:00:00,2025-06-12 00:00:00,17486.810000,3.000000,382.350000
75%,5400.250000,1199.000000,2026-06-27 00:00:00,2026-06-19 00:00:00,31036.540000,11.000000,1966.942500
max,7200.000000,1600.000000,2029-01-08 00:00:00,2029-01-08 00:00:00,202714.470000,49.000000,32340.360000
std,2078.605302,460.078328,NaN,NaN,22567.185597,8.217942,3044.252287

Credit_history

,credit_id,customer_id,credit_score,previous_loans,previous_defaults,active_loans,credit_utilization
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,600.500000,621.731667,688.385833,2.447500,0.224167,1.175833,40.947067
std,346.554469,356.706332,73.900099,1.555397,0.468080,1.088226,19.782961
min,1.000000,1.000000,398.000000,0.000000,0.000000,0.000000,2.000000
25%,300.750000,315.750000,641.750000,1.000000,0.000000,0.000000,25.770000
50%,600.500000,625.000000,688.000000,2.000000,0.000000,1.000000,40.650000
75%,900.250000,942.250000,737.000000,3.000000,0.000000,2.000000,53.760000
max,1200.000000,1200.000000,900.000000,9.000000,3.000000,5.000000,98.000000

Branches

       branch_id
count  30.000000
mean   15.500000
std     8.803408
min     1.000000
25%     8.250000
50%    15.500000
75%    22.750000
max    30.000000

Collateral

       collateral_id      loan_id  collateral_value       valuation_date
count     900.000000   900.000000      9.000000e+02                  900
mean      450.500000   797.867778      2.020443e+06  2024-04-14 10:01:36
min         1.000000     1.000000      3.148571e+04  2022-02-21 00:00:00
25%       225.750000   416.500000      5.477018e+05  2023-07-11 12:00:00
50%       450.500000   756.000000      1.201394e+06  2024-04-03 12:00:00
75%       675.250000  1206.250000      2.668687e+06  2025-01-13 06:00:00
max       900.000000  1598.000000      1.068352e+07  2026-04-09 00:00:00
std       259.951919   458.116761      2.165340e+06                  NaN

Loan_status_history

,status_history_id,loan_id,status_date,days_in_status
count,4500.000000,4500.000000,4500,4500.000000
mean,2250.500000,813.575778,2024-11-21 12:25:16.800000,91.090000
min,1.000000,1.000000,2022-01-18 00:00:00,1.000000
25%,1125.750000,414.750000,2024-01-06 18:00:00,46.000000
50%,2250.500000,816.500000,2024-11-25 00:00:00,91.500000
75%,3375.250000,1215.000000,2025-10-16 00:00:00,137.000000
max,4500.000000,1599.000000,2027-09-21 00:00:00,180.000000
std,1299.182435,463.025139,NaN,52.185426

Loan_recovery

In [20]:
print(customers.duplicated().sum())
print(loan_applications.duplicated().sum())
print(loans.duplicated().sum())
print(loan_payments.duplicated().sum())
print(credit_history.duplicated().sum())
print(branches.duplicated().sum())
print(collateral.duplicated().sum())
print(loan_status_history.duplicated().sum())
print(loan_recovery.duplicated().sum())

0
0
0
0
0
0
0
0
0

In [21]:
customers = customers.drop_duplicates()
loan_applications = loan_applications.drop_duplicates()
loans = loans.drop_duplicates()
loan_payments = loan_payments.drop_duplicates()
credit_history = credit_history.drop_duplicates()
branches = branches.drop_duplicates()
collateral = collateral.drop_duplicates()
loan_status_history = loan_status_history.drop_duplicates()
loan_recovery = loan_recovery.drop_duplicates()

In [22]:
duplicate_summary = pd.DataFrame({
    "Table Name": ["Customers","Loan_Applications","Loans","Loan_Payments","Credit_History","Branches","Collateral","Loan_Status_History","Loan_Recovery"],
    
    "Duplicate Records": [
        customers.duplicated().sum(),
        loan_applications.duplicated().sum(),
        loans.duplicated().sum(),
        loan_payments.duplicated().sum(),
        credit_history.duplicated().sum(),
        branches.duplicated().sum(),
        collateral.duplicated().sum(),
        loan_status_history.duplicated().sum(),
        loan_recovery.duplicated().sum()
    ]})
print(duplicate_summary)

            Table Name  Duplicate Records
0            Customers                  0
1    Loan_Applications                  0
2                Loans                  0
3        Loan_Payments                  0
4       Credit_History                  0
5             Branches                  0
6           Collateral                  0
7  Loan_Status_History                  0
8        Loan_Recovery                  0

In [23]:
c_blank=pd.DataFrame({
    "S.No": range(1, len(customers.columns) + 1),
    "Column Name": customers.columns,
    "Missing Values":customers.isnull().sum().values})
c_blank

    S.No        Column Name  Missing Values
0      1        customer_id               0
1      2         first_name               0
2      3          last_name               0
3      4             gender               0
4      5                age               0
5      6      date_of_birth               0
6      7     marital_status               0
7      8         occupation               0
8      9      annual_income               1
9     10     monthly_income               1
10    11               city               0
11    12              state               0
12    13   customer_segment               0
13    14       credit_score               0
14    15  account_open_date               0

In [24]:
print(customers.isnull().sum())
print(loan_applications.isnull().sum())
print(loans.isnull().sum())
print(loan_payments.isnull().sum())
print(credit_history.isnull().sum())
print(branches.isnull().sum())
print(collateral.isnull().sum())
print(loan_status_history.isnull().sum())
print(loan_recovery.isnull().sum())

customer_id          0
first_name           0
last_name            0
gender               0
age                  0
date_of_birth        0
marital_status       0
occupation           0
annual_income        1
monthly_income       1
city                 0
state                0
customer_segment     0
credit_score         0
account_open_date    0
dtype: int64
application_id      0
customer_id         0
loan_type           0
requested_amount    0
application_date    0
approval_status     0
rejection_reason    0
processing_days     0
dtype: int64
loan_id                0
customer_id            0
branch_id              0
loan_type              0
application_date       0
approval_date          0
loan_amount            1
interest_rate          0
loan_tenure_months     0
emi_amount             0
loan_status            0
outstanding_balance    0
dtype: int64
payment_id        0
loan_id           0
payment_date      0
emi_due_date      0
payment_amount    1
payment_status    0
days_overdue      0
penalty_amount    0
dtype: int64
credit_id             0
customer_id           0
credit_score          0
previous_loans        0
previous_defaults     0
active_loans          0
credit_utilization    0
dtype: int64
branch_id       0
branch_name     0
city            0
state           0
region          0
manager_name    0
dtype: int64
collateral_id        0
loan_id              0
collateral_type      0
collateral_value     0
valuation_date       0
ownership_status     0
collateral_status    0
loan_type            0
valuation_source     0
dtype: int64
status_history_id    0
loan_id              0
status_date          0
previous_status      0
new_status           0
days_in_status       0
reason               0
recorded_by          0
dtype: int64
recovery_id         0
loan_id             0
recovery_date       0
recovery_amount     1
recovery_method     0
recovery_status     0
recovery_cost       0
recovery_officer    0
remarks             0
dtype: int64

In [25]:
customers["annual_income"] = customers["annual_income"].fillna(
    customers["annual_income"].median()
)

customers["monthly_income"] = customers["monthly_income"].fillna(
    customers["monthly_income"].median()
)

loans["loan_amount"] = loans["loan_amount"].fillna(
    loans["loan_amount"].median()
)

loan_payments["payment_amount"] = loan_payments["payment_amount"].fillna(
    loan_payments["payment_amount"].median()
)

loan_recovery["recovery_amount"] = loan_recovery["recovery_amount"].fillna(
    loan_recovery["recovery_amount"].median()
)

In [26]:
c_blank=pd.DataFrame({
    "S.No": range(1, len(customers.columns) + 1),
    "Column Name": customers.columns,
    "Missing Values":customers.isnull().sum().values})
c_blank

    S.No        Column Name  Missing Values
0      1        customer_id               0
1      2         first_name               0
2      3          last_name               0
3      4             gender               0
4      5                age               0
5      6      date_of_birth               0
6      7     marital_status               0
7      8         occupation               0
8      9      annual_income               0
9     10     monthly_income               0
10    11               city               0
11    12              state               0
12    13   customer_segment               0
13    14       credit_score               0
14    15  account_open_date               0

In [27]:
l_blank=pd.DataFrame({
    "S.No": range(1, len(loan_applications.columns) + 1),
    "Column Name": loan_applications.columns,
    "Missing Values":loan_applications.isnull().sum().values})
l_blank

   S.No       Column Name  Missing Values
0     1    application_id               0
1     2       customer_id               0
2     3         loan_type               0
3     4  requested_amount               0
4     5  application_date               0
5     6   approval_status               0
6     7  rejection_reason               0
7     8   processing_days               0

In [28]:
lo_blank=pd.DataFrame({
    "S.No": range(1, len(loans.columns) + 1),
    "Column Name": loans.columns,
    "Missing Values":loans.isnull().sum().values})
lo_blank

    S.No          Column Name  Missing Values
0      1              loan_id               0
1      2          customer_id               0
2      3            branch_id               0
3      4            loan_type               0
4      5     application_date               0
5      6        approval_date               0
6      7          loan_amount               0
7      8        interest_rate               0
8      9   loan_tenure_months               0
9     10           emi_amount               0
10    11          loan_status               0
11    12  outstanding_balance               0

In [29]:
lo_blank=pd.DataFrame({
    "S.No": range(1, len(loans.columns) + 1),
    "Column Name": loans.columns,
    "Missing Values":loans.isnull().sum().values})
lo_blank

    S.No          Column Name  Missing Values
0      1              loan_id               0
1      2          customer_id               0
2      3            branch_id               0
3      4            loan_type               0
4      5     application_date               0
5      6        approval_date               0
6      7          loan_amount               0
7      8        interest_rate               0
8      9   loan_tenure_months               0
9     10           emi_amount               0
10    11          loan_status               0
11    12  outstanding_balance               0

In [30]:
lop_blank=pd.DataFrame({
    "S.No": range(1, len(loan_payments.columns) + 1),
    "Column Name": loan_payments.columns,
    "Missing Values":loan_payments.isnull().sum().values})
lop_blank

   S.No     Column Name  Missing Values
0     1      payment_id               0
1     2         loan_id               0
2     3    payment_date               0
3     4    emi_due_date               0
4     5  payment_amount               0
5     6  payment_status               0
6     7    days_overdue               0
7     8  penalty_amount               0

In [102]:
ch_blank=pd.DataFrame({
    "S.No": range(1, len(credit_history.columns) + 1),
    "Column Name": credit_history.columns,
    "Missing Values":credit_history.isnull().sum().values})
ch_blank

   S.No         Column Name  Missing Values
0     1           credit_id               0
1     2         customer_id               0
2     3        credit_score               0
3     4      previous_loans               0
4     5   previous_defaults               0
5     6        active_loans               0
6     7  credit_utilization               0

In [31]:
b_blank=pd.DataFrame({
    "S.No": range(1, len(branches.columns) + 1),
    "Column Name": branches.columns,
    "Missing Values":branches.isnull().sum().values})
b_blank

   S.No   Column Name  Missing Values
0     1     branch_id               0
1     2   branch_name               0
2     3          city               0
3     4         state               0
4     5        region               0
5     6  manager_name               0

In [32]:
co_blank=pd.DataFrame({
    "S.No": range(1, len(collateral.columns) + 1),
    "Column Name": collateral.columns,
    "Missing Values":collateral.isnull().sum().values})
co_blank

   S.No        Column Name  Missing Values
0     1      collateral_id               0
1     2            loan_id               0
2     3    collateral_type               0
3     4   collateral_value               0
4     5     valuation_date               0
5     6   ownership_status               0
6     7  collateral_status               0
7     8          loan_type               0
8     9   valuation_source               0

In [33]:
loan_status_history.isnull().sum()

status_history_id    0
loan_id              0
status_date          0
previous_status      0
new_status           0
days_in_status       0
reason               0
recorded_by          0
dtype: int64

In [34]:
loan_recovery.isnull().sum()

recovery_id         0
loan_id             0
recovery_date       0
recovery_amount     0
recovery_method     0
recovery_status     0
recovery_cost       0
recovery_officer    0
remarks             0
dtype: int64

In [35]:
for col in customers.select_dtypes(include="object").columns:
    print(col, ":", customers[col].unique())

first_name : <StringArray>
[  'Pooja',   'Rahul',  'Aditya',    'Diya',   'Aarav',  'Shreya',   'Nisha',
   'Sneha',   'Priya',   'Arjun', 'Karthik',  'Ananya',   'Divya',  'Vikram',
   'Rohan',   'Kavya',    'Isha',  'Vivaan',   'Aditi',   'Meera']
Length: 20, dtype: str
last_name : <StringArray>
[ 'Verma',    'Rao',  'Gupta', 'Sharma',  'Menon',   'Iyer',    'Das',
  'Patel',  'Mehta',   'Nair', 'Pillai',  'Joshi',  'Kumar',  'Reddy',
  'Singh']
Length: 15, dtype: str
gender : <StringArray>
['Male', 'Female', 'female']
Length: 3, dtype: str
marital_status : <StringArray>
['Married', 'Single', 'Divorced', 'Widowed']
Length: 4, dtype: str
occupation : <StringArray>
[           'Salaried',       'Self-Employed', 'Government Employee',
        'Professional',             'Retired',      'Business Owner',
             'Student']
Length: 7, dtype: str
city : <StringArray>
[       'Mysuru',       'Lucknow',        'Mumbai',     'New Delhi',
       'Chennai',       'Kolkata',       'Madurai',     'Hyderabad',
         'Kochi',      'Ludhiana',         'Surat', 'Visakhapatnam',
     'Ahmedabad',    'Coimbatore',        'Jaipur',     'Bengaluru',
      'Gurugram',          'Pune']
Length: 18, dtype: str
state : <StringArray>
[     'Karnataka',  'Uttar Pradesh',    'Maharashtra',          'Delhi',
     'Tamil Nadu',    'West Bengal',      'Telangana',         'Kerala',
     '  Punjab  ',        'Gujarat', 'Andhra Pradesh',         'Punjab',
      'Rajasthan',        'Haryana']
Length: 14, dtype: str
customer_segment : <StringArray>
['Affluent', 'Retail', 'Premium']
Length: 3, dtype: str

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_13560\2579680481.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in customers.select_dtypes(include="object").columns:

In [36]:
customers["gender"] = customers["gender"].str.strip().str.title()

In [37]:
print(customers["gender"].unique())

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [38]:
for col in loan_applications.select_dtypes(include="object").columns:
    print(col, ":", loan_applications[col].unique())

loan_type : <StringArray>
['Personal', 'Education', 'Auto', 'Home', 'Business', 'Gold', '  Personal  ']
Length: 7, dtype: str
approval_status : <StringArray>
['Approved', 'Rejected', 'rejected', 'Pending']
Length: 4, dtype: str
rejection_reason : <StringArray>
[           'Not Available', 'Incomplete Documentation',
         'High Debt Burden',         'Low Credit Score',
      'Insufficient Income',   'High Existing Exposure']
Length: 6, dtype: str

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_13560\477637518.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in loan_applications.select_dtypes(include="object").columns:

In [39]:
loan_applications["loan_type"] = loan_applications["loan_type"].str.strip().str.title()
loan_applications["approval_status"] = loan_applications["approval_status"].str.strip().str.title()
loan_applications["rejection_reason"] = (
    loan_applications["rejection_reason"].str.strip()
)

In [40]:
for col in loan_applications.select_dtypes(include="object").columns:
    print(col, ":", loan_applications[col].unique())

loan_type : <StringArray>
['Personal', 'Education', 'Auto', 'Home', 'Business', 'Gold']
Length: 6, dtype: str
approval_status : <StringArray>
['Approved', 'Rejected', 'Pending']
Length: 3, dtype: str
rejection_reason : <StringArray>
[           'Not Available', 'Incomplete Documentation',
         'High Debt Burden',         'Low Credit Score',
      'Insufficient Income',   'High Existing Exposure']
Length: 6, dtype: str

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_13560\477637518.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in loan_applications.select_dtypes(include="object").columns:

In [41]:
print(repr(loan_applications["rejection_reason"].iloc[0]))

'Not Available'

In [44]:
for col in loans.select_dtypes(include="object").columns:
    print(col, ":", loans[col].unique())

loan_type : <StringArray>
['Personal', 'Gold', 'Home', 'Business', 'Auto', 'Education']
Length: 6, dtype: str
loan_status : <StringArray>
['Active', 'Closed', 'Defaulted', '  Active  ', 'ACTIVE']
Length: 5, dtype: str

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_13560\487194434.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in loans.select_dtypes(include="object").columns:

In [46]:
loans["loan_status"] = (loans["loan_status"].str.strip().str.title())

In [48]:
print(loans["loan_status"].unique())

<StringArray>
['Active', 'Closed', 'Defaulted']
Length: 3, dtype: str

In [49]:
for col in loan_payments.select_dtypes(include="object").columns:
    print(col, ":", loan_payments[col].unique())

payment_status : <StringArray>
['Paid', 'Late', '  Late  ', 'paid']
Length: 4, dtype: str

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_13560\3509274111.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in loan_payments.select_dtypes(include="object").columns:

In [51]:
loan_payments["payment_status"] = (loan_payments["payment_status"].str.strip().str.title())

In [52]:
print(loan_payments["payment_status"].unique())

<StringArray>
['Paid', 'Late']
Length: 2, dtype: str

In [54]:
for col in credit_history.select_dtypes(include="object").columns:
    print(col, ":", credit_history[col].unique())

In [56]:
for col in branches.select_dtypes(include="object").columns:
    print(col, ":", branches[col].unique())

branch_name : <StringArray>
[      'Chennai Branch 1',    'Coimbatore Branch 1',       'Madurai Branch 1',
     'Bengaluru Branch 1',        'Mysuru Branch 1',        'Mumbai Branch 1',
          'Pune Branch 1',     'Hyderabad Branch 1',     'New Delhi Branch 1',
       'Kolkata Branch 1',     'Ahmedabad Branch 1',         'Surat Branch 1',
        'Jaipur Branch 1',         'Kochi Branch 1',       'Lucknow Branch 1',
      'Ludhiana Branch 1',      'Gurugram Branch 1', 'Visakhapatnam Branch 1',
       'Chennai Branch 2',    'Coimbatore Branch 2',       'Madurai Branch 2',
     'Bengaluru Branch 2',        'Mysuru Branch 2',        'Mumbai Branch 2',
          'Pune Branch 2',     'Hyderabad Branch 2',     'New Delhi Branch 2',
       'Kolkata Branch 2',     'Ahmedabad Branch 2',         'Surat Branch 2']
Length: 30, dtype: str
city : <StringArray>
[      'Chennai',    'Coimbatore',       'Madurai',     'Bengaluru',
        'Mysuru',        'Mumbai',          'Pune',     'Hyderabad',
     'New Delhi',       'Kolkata',     'Ahmedabad',         'Surat',
        'Jaipur',         'Kochi',       'Lucknow',      'Ludhiana',
      'Gurugram', 'Visakhapatnam']
Length: 18, dtype: str
state : <StringArray>
[    'Tamil Nadu',      'Karnataka',    'Maharashtra',      'Telangana',
          'Delhi',    'West Bengal',        'Gujarat',      'Rajasthan',
         'Kerala',  'Uttar Pradesh',         'Punjab',        'Haryana',
 'Andhra Pradesh']
Length: 13, dtype: str
region : <StringArray>
['South', 'West', '  South  ', 'North', 'East']
Length: 5, dtype: str
manager_name : <StringArray>
['Manager 001', 'Manager 002', 'Manager 003', 'Manager 004', 'Manager 005',
 'Manager 006', 'Manager 007', 'Manager 008', 'Manager 009', 'Manager 010',
 'Manager 011', 'Manager 012', 'Manager 013', 'Manager 014', 'Manager 015',
 'Manager 016', 'Manager 017', 'Manager 018', 'Manager 019', 'Manager 020',
 'Manager 021', 'Manager 022', 'Manager 023', 'Manager 024', 'Manager 025',
 'Manager 026', 'Manager 027', 'Manager 028', 'Manager 029', 'Manager 030']
Length: 30, dtype: str

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_13560\3739545343.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in branches.select_dtypes(include="object").columns:

In [57]:
branches["region"] = (branches["region"].str.strip().str.title())

In [58]:
print(branches["region"].unique())

<StringArray>
['South', 'West', 'North', 'East']
Length: 4, dtype: str

In [59]:
for col in collateral.select_dtypes(include="object").columns:
    print(col, ":", collateral[col].unique())

collateral_type : <StringArray>
['Property', 'Vehicle', 'Gold', 'Equipment', 'Fixed Deposit']
Length: 5, dtype: str
ownership_status : <StringArray>
['Customer Owned', 'Jointly Owned', 'CUSTOMER OWNED']
Length: 3, dtype: str
collateral_status : <StringArray>
['Active', 'Released', 'Seized']
Length: 3, dtype: str
loan_type : <StringArray>
['Auto', 'Business', 'Home', 'Personal', 'Education', 'Gold']
Length: 6, dtype: str
valuation_source : <StringArray>
['Bank Approved Valuer', 'External Valuer']
Length: 2, dtype: str

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_13560\2284676055.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in collateral.select_dtypes(include="object").columns:

In [60]:
collateral["ownership_status"] = (collateral["ownership_status"].str.strip().str.title())

In [61]:
print(collateral["ownership_status"].unique())

<StringArray>
['Customer Owned', 'Jointly Owned']
Length: 2, dtype: str

In [62]:
for col in loan_status_history.select_dtypes(include="object").columns:
    print(col, ":", loan_status_history[col].unique())

previous_status : <StringArray>
['Recovery', 'Active', 'Overdue']
Length: 3, dtype: str
new_status : <StringArray>
['Closed', 'Overdue', 'Active', 'Defaulted']
Length: 4, dtype: str
reason : <StringArray>
['Recovery Initiated',        'Risk Review',     'Payment Missed',
       'Loan Settled', 'Regular Monitoring',        'EMI Overdue']
Length: 6, dtype: str
recorded_by : <StringArray>
['Collections Team', 'Credit Officer', 'Loan Monitoring System']
Length: 3, dtype: str

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_13560\3243261243.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in loan_status_history.select_dtypes(include="object").columns:

In [63]:
for col in loan_recovery.select_dtypes(include="object").columns:
    print(col, ":", loan_recovery[col].unique())

recovery_method : <StringArray>
['Legal Recovery', 'Direct Payment', 'Settlement', 'Collateral Sale']
Length: 4, dtype: str
recovery_status : <StringArray>
['Full', 'Partial']
Length: 2, dtype: str
recovery_officer : <StringArray>
['Officer 344', 'Officer 324', 'Officer 106', 'Officer 176', 'Officer 278',
 'Officer 575', 'Officer 477', 'Officer 889', 'Officer 565', 'Officer 653',
 ...
 'Officer 833', 'Officer 719', 'Officer 989', 'Officer 998', 'Officer 549',
 'Officer 155', 'Officer 355', 'Officer 943', 'Officer 872', 'Officer 139']
Length: 316, dtype: str
remarks : <StringArray>
[ 'Settlement payment', 'Collateral proceeds',    'Legal collection',
  'Scheduled recovery']
Length: 4, dtype: str

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_13560\1739562518.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in loan_recovery.select_dtypes(include="object").columns:

In [64]:
print(customers.columns)
print(loan_applications.columns)
print(loans.columns)
print(loan_payments.columns)
print(loan_status_history.columns)
print(loan_recovery.columns)
print(collateral.columns)
print(branches.columns)
print(credit_history.columns)

Index(['customer_id', 'first_name', 'last_name', 'gender', 'age',
       'date_of_birth', 'marital_status', 'occupation', 'annual_income',
       'monthly_income', 'city', 'state', 'customer_segment', 'credit_score',
       'account_open_date'],
      dtype='str')
Index(['application_id', 'customer_id', 'loan_type', 'requested_amount',
       'application_date', 'approval_status', 'rejection_reason',
       'processing_days'],
      dtype='str')
Index(['loan_id', 'customer_id', 'branch_id', 'loan_type', 'application_date',
       'approval_date', 'loan_amount', 'interest_rate', 'loan_tenure_months',
       'emi_amount', 'loan_status', 'outstanding_balance'],
      dtype='str')
Index(['payment_id', 'loan_id', 'payment_date', 'emi_due_date',
       'payment_amount', 'payment_status', 'days_overdue', 'penalty_amount'],
      dtype='str')
Index(['status_history_id', 'loan_id', 'status_date', 'previous_status',
       'new_status', 'days_in_status', 'reason', 'recorded_by'],
      dtype='str')
Index(['recovery_id', 'loan_id', 'recovery_date', 'recovery_amount',
       'recovery_method', 'recovery_status', 'recovery_cost',
       'recovery_officer', 'remarks'],
      dtype='str')
Index(['collateral_id', 'loan_id', 'collateral_type', 'collateral_value',
       'valuation_date', 'ownership_status', 'collateral_status', 'loan_type',
       'valuation_source'],
      dtype='str')
Index(['branch_id', 'branch_name', 'city', 'state', 'region', 'manager_name'], dtype='str')
Index(['credit_id', 'customer_id', 'credit_score', 'previous_loans',
       'previous_defaults', 'active_loans', 'credit_utilization'],
      dtype='str')

In [65]:
customers["account_open_date"] = pd.to_datetime(
    customers["account_open_date"], errors="coerce"
)

loan_applications["application_date"] = pd.to_datetime(
    loan_applications["application_date"], errors="coerce"
)

loans["approval_date"] = pd.to_datetime(
    loans["approval_date"], errors="coerce"
)

loan_payments["emi_due_date"] = pd.to_datetime(
    loan_payments["emi_due_date"], errors="coerce"
)

loan_payments["payment_date"] = pd.to_datetime(
    loan_payments["payment_date"], errors="coerce"
)

loan_status_history["status_date"] = pd.to_datetime(
    loan_status_history["status_date"], errors="coerce"
)

loan_recovery["recovery_date"] = pd.to_datetime(
    loan_recovery["recovery_date"], errors="coerce"
)

In [66]:
print(customers["account_open_date"].isna().sum())
print(loan_applications["application_date"].isna().sum())
print(loans["approval_date"].isna().sum())
print(loan_payments["emi_due_date"].isna().sum())
print(loan_payments["payment_date"].isna().sum())
print(loan_status_history["status_date"].isna().sum())
print(loan_recovery["recovery_date"].isna().sum())

0
0
0
0
0
0
0

In [67]:
print(customers.dtypes)
print(loans.dtypes)
print(loan_payments.dtypes)
print(loan_recovery.dtypes)
print(collateral.dtypes)

customer_id                   int64
first_name                      str
last_name                       str
gender                          str
age                           int64
date_of_birth        datetime64[us]
marital_status                  str
occupation                      str
annual_income               float64
monthly_income              float64
city                            str
state                           str
customer_segment                str
credit_score                  int64
account_open_date    datetime64[us]
dtype: object
loan_id                         int64
customer_id                     int64
branch_id                       int64
loan_type                         str
application_date       datetime64[us]
approval_date          datetime64[us]
loan_amount                   float64
interest_rate                 float64
loan_tenure_months              int64
emi_amount                    float64
loan_status                       str
outstanding_balance           float64
dtype: object
payment_id                 int64
loan_id                    int64
payment_date      datetime64[us]
emi_due_date      datetime64[us]
payment_amount           float64
payment_status               str
days_overdue               int64
penalty_amount           float64
dtype: object
recovery_id                  int64
loan_id                      int64
recovery_date       datetime64[us]
recovery_amount            float64
recovery_method                str
recovery_status                str
recovery_cost              float64
recovery_officer               str
remarks                        str
dtype: object
collateral_id                 int64
loan_id                       int64
collateral_type                 str
collateral_value            float64
valuation_date       datetime64[us]
ownership_status                str
collateral_status               str
loan_type                       str
valuation_source                str
dtype: object

In [68]:
customers["age"] = pd.to_numeric(
    customers["age"], errors="coerce"
)

customers["annual_income"] = pd.to_numeric(
    customers["annual_income"], errors="coerce"
)

customers["credit_score"] = pd.to_numeric(
    customers["credit_score"], errors="coerce"
)

In [69]:
loans["loan_amount"] = pd.to_numeric(
    loans["loan_amount"], errors="coerce"
)

loans["interest_rate"] = pd.to_numeric(
    loans["interest_rate"], errors="coerce"
)

loans["emi_amount"] = pd.to_numeric(
    loans["emi_amount"], errors="coerce"
)

loans["outstanding_balance"] = pd.to_numeric(
    loans["outstanding_balance"], errors="coerce"
)

In [70]:
loan_payments["payment_amount"] = pd.to_numeric(
    loan_payments["payment_amount"], errors="coerce"
)

loan_payments["days_overdue"] = pd.to_numeric(
    loan_payments["days_overdue"], errors="coerce"
)

In [71]:
loan_recovery["recovery_amount"] = pd.to_numeric(
    loan_recovery["recovery_amount"], errors="coerce"
)

In [72]:
collateral["collateral_value"] = pd.to_numeric(
    collateral["collateral_value"], errors="coerce"
)

In [73]:
print(customers.dtypes)
print(loans.dtypes)
print(loan_payments.dtypes)
print(loan_recovery.dtypes)
print(collateral.dtypes)

customer_id                   int64
first_name                      str
last_name                       str
gender                          str
age                           int64
date_of_birth        datetime64[us]
marital_status                  str
occupation                      str
annual_income               float64
monthly_income              float64
city                            str
state                           str
customer_segment                str
credit_score                  int64
account_open_date    datetime64[us]
dtype: object
loan_id                         int64
customer_id                     int64
branch_id                       int64
loan_type                         str
application_date       datetime64[us]
approval_date          datetime64[us]
loan_amount                   float64
interest_rate                 float64
loan_tenure_months              int64
emi_amount                    float64
loan_status                       str
outstanding_balance           float64
dtype: object
payment_id                 int64
loan_id                    int64
payment_date      datetime64[us]
emi_due_date      datetime64[us]
payment_amount           float64
payment_status               str
days_overdue               int64
penalty_amount           float64
dtype: object
recovery_id                  int64
loan_id                      int64
recovery_date       datetime64[us]
recovery_amount            float64
recovery_method                str
recovery_status                str
recovery_cost              float64
recovery_officer               str
remarks                        str
dtype: object
collateral_id                 int64
loan_id                       int64
collateral_type                 str
collateral_value            float64
valuation_date       datetime64[us]
ownership_status                str
collateral_status               str
loan_type                       str
valuation_source                str
dtype: object

In [74]:
customers["age_valid"] = customers["age"] > 0

print("Invalid Age Records:")
print(customers[customers["age_valid"] == False])

Invalid Age Records:
     customer_id first_name last_name  gender  age date_of_birth  \
151          152      Sneha      Nair  Female   -5    1988-09-01

    marital_status occupation  annual_income  monthly_income        city  \
151         Single   Salaried      946043.21        78836.93  Coimbatore

          state customer_segment  credit_score account_open_date  age_valid
151  Tamil Nadu         Affluent           684        2015-11-15      False

In [76]:
today = pd.Timestamp.today()

customers["age"] = (
    today.year - customers["date_of_birth"].dt.year
    - (
        (customers["date_of_birth"].dt.month > today.month)
        |
        (
            (customers["date_of_birth"].dt.month == today.month)
            & (customers["date_of_birth"].dt.day > today.day)
        )
    ).astype(int)
)

In [77]:
customers.loc[
    customers["customer_id"] == 152,
    ["customer_id", "date_of_birth", "age"]
]

     customer_id date_of_birth  age
151          152    1988-09-01   37

In [78]:
customers["credit_score_valid"] = (
    customers["credit_score"].between(300, 850)
)

print("Invalid Credit Score Records:")
print(
    customers[
        customers["credit_score_valid"] == False
    ]
)

Invalid Credit Score Records:
      customer_id first_name last_name  gender  age date_of_birth  \
101           102     Shreya     Singh    Male   64    1962-01-24
182           183      Rahul     Mehta    Male   57    1969-03-22
259           260     Aditya     Kumar    Male   64    1962-01-21
300           301      Nisha       Rao    Male   50    1975-12-14
402           403      Kavya      Iyer  Female   57    1968-12-13
493           494      Sneha      Nair  Female   39    1986-10-24
545           546      Priya       Das    Male   45    1981-01-20
613           614      Meera     Joshi    Male   43    1982-09-10
617           618    Karthik       Das  Female   50    1975-10-13
718           719      Aditi       Das  Female   40    1986-01-26
776           777     Vivaan       Rao    Male   55    1971-04-17
1137         1138      Priya       Das    Male   45    1981-01-20

     marital_status           occupation  annual_income  monthly_income  \
101         Widowed              Student     1272734.65       106061.22
182         Married             Salaried      976299.62        81358.30
259          Single       Business Owner      984394.13        82032.84
300          Single        Self-Employed      374453.06        31204.42
402          Single  Government Employee      704398.87        58699.91
493         Married             Salaried      456149.02        38012.42
545         Married  Government Employee      668074.86        55672.90
613         Married  Government Employee      534063.97        44505.33
617        Divorced         Professional      525732.05        43811.00
718          Single             Salaried     1334686.37       111223.86
776         Married  Government Employee     1364548.05       113712.34
1137        Married  Government Employee      668074.86        55672.90

           city        state customer_segment  credit_score account_open_date  \
101      Jaipur    Rajasthan         Affluent           950        2019-05-25
182      Mysuru    Karnataka         Affluent           866        2024-04-17
259    Gurugram      Haryana         Affluent           860        2019-12-06
300      Mysuru    Karnataka           Retail           894        2020-11-19
402    Gurugram      Haryana         Affluent           884        2018-11-10
493   New Delhi        Delhi           Retail           889        2021-09-05
545   Bengaluru    Karnataka           Retail           870        2018-08-23
613   Bengaluru    Karnataka           Retail           900        2019-09-21
617       Kochi       Kerala           Retail           892        2017-04-22
718     Chennai   Tamil Nadu          Premium           875        2017-03-06
776        Pune  Maharashtra          Premium           857        2015-08-15
1137  Bengaluru    Karnataka           Retail           870        2018-08-23

      age_valid  credit_score_valid
101        True               False
182        True               False
259        True               False
300        True               False
402        True               False
493        True               False
545        True               False
613        True               False
617        True               False
718        True               False
776        True               False
1137       True               False

In [79]:
print(
    "Invalid Credit Scores:",
    (~customers["credit_score_valid"]).sum()
)

Invalid Credit Scores: 12

In [80]:
print(
    customers.loc[
        customers["credit_score_valid"] == False,
        ["customer_id", "credit_score"]
    ]
)

      customer_id  credit_score
101           102           950
182           183           866
259           260           860
300           301           894
402           403           884
493           494           889
545           546           870
613           614           900
617           618           892
718           719           875
776           777           857
1137         1138           870

In [81]:
print(
    customers.loc[
        customers["credit_score_valid"] == False,
        "credit_score"
    ].unique()
)

[950 866 860 894 884 889 870 900 892 875 857]

In [82]:
valid_median = customers.loc[
    customers["credit_score_valid"],
    "credit_score"
].median()

customers.loc[
    customers["credit_score_valid"] == False,
    "credit_score"
] = valid_median

In [83]:
customers["credit_score_valid"] = (
    customers["credit_score"].between(300, 850)
)

print(
    "Invalid Credit Scores:",
    (~customers["credit_score_valid"]).sum()
)

Invalid Credit Scores: 0

In [84]:
loans["loan_amount_valid"] = loans["loan_amount"] > 0

print("Invalid Loan Amount Records:")
print(
    loans[
        loans["loan_amount_valid"] == False
    ]
)

Invalid Loan Amount Records:
Empty DataFrame
Columns: [loan_id, customer_id, branch_id, loan_type, application_date, approval_date, loan_amount, interest_rate, loan_tenure_months, emi_amount, loan_status, outstanding_balance, loan_amount_valid]
Index: []

In [85]:
print(
    "Invalid Loan Amounts:",
    (~loans["loan_amount_valid"]).sum()
)

Invalid Loan Amounts: 0

In [86]:
print(
    loans.loc[
        loans["loan_amount_valid"] == False,
        ["loan_id", "loan_amount"]
    ]
)

Empty DataFrame
Columns: [loan_id, loan_amount]
Index: []

In [87]:
loans["interest_rate_valid"] = (
    loans["interest_rate"].between(0, 30)
)

print("Invalid Interest Rate Records:")
print(
    loans[
        loans["interest_rate_valid"] == False
    ]
)

Invalid Interest Rate Records:
     loan_id  customer_id  branch_id loan_type application_date approval_date  \
301      302          499         11  Personal       2022-08-19    2022-08-21

     loan_amount  interest_rate  loan_tenure_months  emi_amount loan_status  \
301   1285425.83           75.0                  75    25921.95      Active

     outstanding_balance  loan_amount_valid  interest_rate_valid
301            548408.57               True                False

In [88]:
print(
    "Invalid Interest Rates:",
    (~loans["interest_rate_valid"]).sum()
)

Invalid Interest Rates: 1

In [89]:
print(
    loans.loc[
        loans["interest_rate_valid"] == False,
        ["loan_id", "interest_rate"]
    ]
)

     loan_id  interest_rate
301      302           75.0

In [90]:
print(
    loans.loc[
        loans["interest_rate_valid"] == False,
        "interest_rate"
    ].values
)

[75.]

In [91]:
loan_payments["payment_amount_valid"] = (
    loan_payments["payment_amount"] > 0
)

print("Invalid Payment Amount Records:")
print(
    loan_payments[
        loan_payments["payment_amount_valid"] == False
    ]
)

Invalid Payment Amount Records:
Empty DataFrame
Columns: [payment_id, loan_id, payment_date, emi_due_date, payment_amount, payment_status, days_overdue, penalty_amount, payment_amount_valid]
Index: []

In [92]:
print(
    "Invalid Payment Amounts:",
    (~loan_payments["payment_amount_valid"]).sum()
)

Invalid Payment Amounts: 0

In [93]:
loan_recovery["recovery_amount_valid"] = (
    loan_recovery["recovery_amount"] >= 0
)

print("Invalid Recovery Amount Records:")
print(
    loan_recovery[
        loan_recovery["recovery_amount_valid"] == False
    ]
)

Invalid Recovery Amount Records:
Empty DataFrame
Columns: [recovery_id, loan_id, recovery_date, recovery_amount, recovery_method, recovery_status, recovery_cost, recovery_officer, remarks, recovery_amount_valid]
Index: []

In [94]:
loan_payments["days_overdue_valid"] = (
    loan_payments["days_overdue"] >= 0
)

print("Invalid Days Overdue Records:")
print(
    loan_payments[
        loan_payments["days_overdue_valid"] == False
    ]
)

Invalid Days Overdue Records:
     payment_id  loan_id payment_date emi_due_date  payment_amount  \
401         402      274   2026-03-30   2026-03-30         4515.96

    payment_status  days_overdue  penalty_amount  payment_amount_valid  \
401           Paid           -10             0.0                  True

     days_overdue_valid
401               False

In [95]:
print(
    "Invalid Days Overdue:",
    (~loan_payments["days_overdue_valid"]).sum()
)

Invalid Days Overdue: 1

In [96]:
print(
    loan_payments.loc[
        loan_payments["days_overdue_valid"] == False,
        ["payment_id", "loan_id", "days_overdue"]
    ]
)

     payment_id  loan_id  days_overdue
401         402      274           -10

In [97]:
loan_payments.loc[
    loan_payments["days_overdue"] < 0,
    "days_overdue"
] = 0

In [98]:
loan_payments["days_overdue_valid"] = (
    loan_payments["days_overdue"] >= 0
)

print(
    "Invalid Days Overdue:",
    (~loan_payments["days_overdue_valid"]).sum()
)

Invalid Days Overdue: 0

In [99]:
valid_status = [
    "Active",
    "Closed",
    "Defaulted",
    "Recovery"
]

loans["loan_status_valid"] = (
    loans["loan_status"].isin(valid_status)
)

print("Invalid Loan Status Records:")
print(
    loans[
        loans["loan_status_valid"] == False
    ]
)

Invalid Loan Status Records:
Empty DataFrame
Columns: [loan_id, customer_id, branch_id, loan_type, application_date, approval_date, loan_amount, interest_rate, loan_tenure_months, emi_amount, loan_status, outstanding_balance, loan_amount_valid, interest_rate_valid, loan_status_valid]
Index: []

In [100]:
customers.to_csv("customers_clean.csv", index=False)

loan_applications.to_csv("loan_applications_clean.csv", index=False)

loans.to_csv("loans_clean.csv", index=False)

loan_payments.to_csv("loan_payments_clean.csv", index=False)

credit_history.to_csv("credit_history_clean.csv", index=False)

branches.to_csv("branches_clean.csv", index=False)

collateral.to_csv("collateral_clean.csv", index=False)

loan_status_history.to_csv("loan_status_history_clean.csv", index=False)

loan_recovery.to_csv("loan_recovery_clean.csv", index=False)

In [101]:
import os

for file in [
    "customers_clean.csv",
    "loan_applications_clean.csv",
    "loans_clean.csv",
    "loan_payments_clean.csv",
    "credit_history_clean.csv",
    "branches_clean.csv",
    "collateral_clean.csv",
    "loan_status_history_clean.csv",
    "loan_recovery_clean.csv"
]:
    print(file, "→", os.path.exists(file))

customers_clean.csv → True
loan_applications_clean.csv → True
loans_clean.csv → True
loan_payments_clean.csv → True
credit_history_clean.csv → True
branches_clean.csv → True
collateral_clean.csv → True
loan_status_history_clean.csv → True
loan_recovery_clean.csv → True

In [102]:
print(os.getcwd())

C:\Users\ELCOT